### ISSUE TITLE
Sort out values where the operating parameters of sensors arent met

### ISSUE THREAD

**Issue by Tachmeton** [decentral-air-monitoring/esp32#31]
Operating parameters can be heat, pressure and humidity and values of the air qualtity sensor should be discarded. Have to declare if they should be discarded and the sensor should send an error message or the backend discards the sensor readings.

**Comment by ffly90** [comment]
-300000 values are being discarded by the backend. There is also a status code for no environmental sensor. Is there anything you'd like to have me done?

**Comment by ffly90** [comment]
resolved in my eyes
