### ISSUE TITLE
SDS011 stops the UART Connection to 

### ISSUE THREAD

**Issue by Tachmeton** [decentral-air-monitoring/esp32#6]
If the Microcontroller is not connected to SDS011 it still can read data on the ports.
So which port is selected is not the issue.

**Comment by margau** [comment]
Possibly an hardware problem? Either power supply or USB->UART? I would suggest to verify the following stuff:

- does it work with an external UART->USB-dongle?

if so, we know that the Primary ESP32-UART is not affected, and it's probably an problem with the embedded USB->UART-Chip. In this case I'd suggest to try the if this does also happen when the SDS011 is connected to an external power source? Further steps could be looking onto VCC with an oscilloscope and maybe using some capacitors to eliminate the problems.

If it doesn't work with an external USB->UART, we should investigate if the esp32 is still running (verify e.g. with an blinking led)?

**Comment by margau** [comment]
Current findings:
- ESP32 continues running, only CP2102 (UART<->Serial) crashes
- WiFi (Ping) works fine after SDS011 powered up
- at least Receiving Data via external UART works
- Capacitor (had 330u laying around) between 5V and GND seems to solve the problem
